name: Revert Commit

on:
  workflow_dispatch:
    permissions:
      teams: [myteam]
    inputs:
      branch:
        description: 'Branch name'
        required: true
      commit_id:
        description: 'Commit Id'
        required: true

jobs:
  revert_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Check team membership
      run: |
        team_name="gm-maintainers"
        member_login=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/orgs/greyorange/teams/$team_name/members" | jq --raw-output ".[].login")

        if [[ $member_login =~ "${{ github.actor }}" ]]; then
          echo "User is a member of the specified team. Proceeding with the workflow..."
        else
          echo "User is not a member of the specified team. Workflow execution stopped."
          exit 1
        fi
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PUSH_PAT }}

    - name: Set Git user identity
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Revert commit
      run: |
        git checkout ${{ inputs.branch }}
        git revert --no-edit ${{ inputs.commit_id }}
      
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GH_PUSH_PAT }}
        branch: ${{ inputs.branch }}
