name: Revert Commit

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
      commit_id:
        description: 'Commit ID'
        required: true

jobs:
  revert_commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Revert commit
      run: |
        git checkout ${{ inputs.branch }}
        git revert -s recursive -Xtheirs ${{ inputs.commit_id }}
      
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ inputs.branch }}
