name: Revert Commit

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
      commit_id:
        description: 'Commit Id'
        required: true

jobs:
  revert_commit:
    runs-on: ubuntu-latest
    steps:
    - uses: TheModdingInquisition/actions-team-membership@v1.0
      with:
        organization: greyorange 
        team: ${{ vars.MAINTAINERS_TEAM_NAME }}
        token: ${{ secrets.GH_PUSH_PAT }}
        comment: 'Permission Denied'      
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Revert commit
      run: |
        git checkout ${{ inputs.branch }}
        git revert --no-commit ${{ inputs.commit_id }}
    - id: auto-commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Revert commit ${{ inputs.commit_id }}"
        skip_fetch: true
        skip_checkout: true
        branch: ${{ inputs.branch }}
